// Copies latin woff2 files out of @fontsource into static/fonts and regenerates
// the generated half of static/styles/fonts.css. Run: bun run vendor-fonts
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const MARKER = "/* Sans fonts below are generated by scripts/vendor-fonts.mjs; edit the map there. */";

const families = {
  "Inter": "inter",
  "Open Sans": "open-sans",
  "Noto Sans": "noto-sans",
  "Roboto": "roboto",
  "Source Sans 3": "source-sans-3",
  "IBM Plex Sans": "ibm-plex-sans",
  "Lato": "lato",
  "Nunito Sans": "nunito-sans",
  "Work Sans": "work-sans",
  "Fira Sans": "fira-sans",
  "DM Sans": "dm-sans",
  "Atkinson Hyperlegible": "atkinson-hyperlegible",
};

const lines = [];
for (const [family, pkg] of Object.entries(families)) {
  for (const weight of [400, 700]) {
    for (const style of ["normal", "italic"]) {
      const file = `${pkg}-latin-${weight}-${style}.woff2`;
      copyFileSync(`${root}node_modules/@fontsource/${pkg}/files/${file}`, `${root}static/fonts/${file}`);
      lines.push(`@font-face { font-family: "${family}"; src: url("../fonts/${file}") format("woff2"); font-weight: ${weight}; font-style: ${style}; font-display: swap; }`);
    }
  }
}

const css = `${root}static/styles/fonts.css`;
const head = readFileSync(css, "utf8").split(MARKER)[0].trimEnd();
writeFileSync(css, `${head}\n\n${MARKER}\n${lines.join("\n")}\n`);
console.log(`vendored ${lines.length} sans faces`);
